entities:
  - name: "kotlin-stdlib"
    version: "1.2.21"
    dependencies:
      - type: "implementation"
        values:
          - "org.jetbrains.kotlin:kotlin-stdlib"

  - name: "support"
    version: "27.0.2"
    dependencies:
      - type: "implementation"
        values:
          - "com.android.support:appcompat-v7"
          - "com.android.support:support-annotations"

  - name: "dagger"
    version: "2.14.1"
    dependencies:
      - type: "implementation"
        values:
          - "com.google.dagger:dagger"
      - type: "kapt"
        values:
          - "com.google.dagger:dagger-compiler"

  - name: "timber"
    version: "4.6.0"
    dependencies:
      - type: "implementation"
        values:
          - "com.jakewharton.timber:timber"

  - name: "rxjava"
    version: "2.1.9"
    dependencies:
      - type: "implementation"
        values:
          - "io.reactivex.rxjava2:rxjava"

  - name: "rxandroid"
    version: "2.0.2"
    dependencies:
      - type: "implementation"
        values:
          - "io.reactivex.rxjava2:rxandroid"

  - name: "rxbinding"
    version: "2.1.1"
    dependencies:
      - type: "implementation"
        values:
          - "com.jakewharton.rxbinding2:rxbinding"
          - "com.jakewharton.rxbinding2:rxbinding-support-v4"
          - "com.jakewharton.rxbinding2:rxbinding-appcompat-v7"
          - "com.jakewharton.rxbinding2:rxbinding-design"
          - "com.jakewharton.rxbinding2:rxbinding-kotlin"
          - "com.jakewharton.rxbinding2:rxbinding-support-v4-kotlin"
          - "com.jakewharton.rxbinding2:rxbinding-appcompat-v7-kotlin"
          - "com.jakewharton.rxbinding2:rxbinding-design-kotlin"

  - name: "inject"
    version: "1"
    dependencies:
      - type: "implementation"
        values:
          - "javax.inject:javax.inject"

  - name: "annotation-api"
    version: "1.3.1"
    dependencies:
      - type: "compileOnly"
        values:
          - "javax.annotation:javax.annotation-api"
