entities:
  - name: "kotlin-stdlib"
    version: "1.1.4-3"
    dependencies:
      - type: "implementation"
        values:
          - "org.jetbrains.kotlin:kotlin-stdlib"

  - name: "support"
    version: "26.0.2"
    dependencies:
      - type: "implementation"
        values:
          - "com.android.support:appcompat-v7"
          - "com.android.support:support-annotations"

  - name: "dagger"
    version: "2.11"
    dependencies:
      - type: "implementation"
        values:
          - "com.google.dagger:dagger"
      - type: "kapt"
        values:
          - "com.google.dagger:dagger-compiler"

  - name: "butterknife"
    version: "8.8.1"
    dependencies:
      - type: "implementation"
        values:
          - "com.jakewharton:butterknife"
      - type: "kapt"
        values:
          - "com.jakewharton:butterknife-compiler"

  - name: "timber"
    version: "4.5.1"
    dependencies:
      - type: "implementation"
        values:
          - "com.jakewharton.timber:timber"

  - name: "rxjava"
    version: "2.1.3"
    dependencies:
      - type: "implementation"
        values:
          - "io.reactivex.rxjava2:rxjava"

  - name: "rxandroid"
    version: "2.0.1"
    dependencies:
      - type: "implementation"
        values:
          - "io.reactivex.rxjava2:rxandroid"

  - name: "rxbinding"
    version: "2.0.0"
    dependencies:
      - type: "implementation"
        values:
          - "com.jakewharton.rxbinding2:rxbinding"
          - "com.jakewharton.rxbinding2:rxbinding-support-v4"
          - "com.jakewharton.rxbinding2:rxbinding-appcompat-v7"
          - "com.jakewharton.rxbinding2:rxbinding-kotlin"
          - "com.jakewharton.rxbinding2:rxbinding-support-v4-kotlin"
          - "com.jakewharton.rxbinding2:rxbinding-appcompat-v7-kotlin"

  - name: "inject"
    version: "1"
    dependencies:
      - type: "implementation"
        values:
          - "javax.inject:javax.inject"

  - name: "annotation-api"
    version: "1.3"
    dependencies:
      - type: "compileOnly"
        values:
          - "javax.annotation:javax.annotation-api"
